### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by khrystoph** [khrystoph/AWS_ED#5]
Create unit testing for the golang version of this code to prevent regressions in the future.

**Comment by g-bhagat** [comment]
@khrystoph do you still need this?

**Comment by khrystoph** [comment]
Hey, sorry I didn't respond sooner. I'm still working on updating unit testing. I'm doing a re-write and starting with unit testing (and will also add fuzz testing) as I roll out the new version of this which is compatible with go 1.19 and aws sdk v2.

I'm starting with a testing-first approach and haven't included much of that testing in the git repo just yet, but I do have unit testing I'm building along-side the existing functions I'm building, it's just not mocked yet and using specific sites (my own domain) as well as hosted zone IDs.

When I push the unit testing, I intend to have full mocks, along with fuzz testing (fuzz testing will come after the go 1.19 compatible release) and since I'm doing the work together, I shouldn't need outside unit testing, but would welcome additional testing such as additional unit tests and integration testing.

I also intend to have binaries to release for major distributions (Linux, Mac) and architectures (x86 and ARM).
